relationships:
  - name: k8sDeploymentContainsPodStg
    version: "1"
    origins: 
      - Kubernetes Integration
    conditions:
      - attribute: eventType
        anyOf: [ "K8sPodSample" ]
    relationship:
      expires: P75M
      relationshipType: CONTAINS
      source:
        buildGuid:
          account:
            lookup: true 
          domain:
            value: INFRA
          type:
            value: KUBERNETES_DEPLOYMENT
            valueInGuid: NA
          identifier:
            fragments:
              - value: "k8s:"
              - attribute: clusterName
              - value: ":"
              - attribute: namespaceName
              - value: ":deployment:"
              - attribute: deploymentName
            hashAlgorithm: FARM_HASH
      target:
        extractGuid:
          attribute: entityGuid
          entityType:
            value: KUBERNETES_POD
  - name: otelKsmK8sDeploymentManagesPodStg
    # use kube-state-metrics kube_deployment_status_condition metric
    version: "1"
    origins: 
      - OpenTelemetry
    conditions:
      - attribute: metricName
        anyOf: [ "kube_deployment_status_condition" ]
      - attribute: newrelicOnly
        anyOf: [ "true" ]
    relationship:
      expires: P75M
      relationshipType: MANAGES
      source:
        buildGuid:
          account:
            lookup: true  
          domain:
            value: INFRA
          type:
            value: KUBERNETES_DEPLOYMENT
          identifier:
            fragments:
              - attribute: k8s.cluster.name
              - value: ":"
              - attribute: k8s.namespace.name
              - value: ":"
              - attribute: k8s.deployment.name
            hashAlgorithm: FARM_HASH
      target:
        extractGuid:
          attribute: entity.guid
          entityType:
            value: KUBERNETES_POD